appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: h+FmlJTM/bgIcf9FKqGLMTtkOwpCWlh1XD5qBYIsTmVnnynE4q0Yq86F9XsWk9P2O8HZb1bKZvPj3m9kuUNLyucDOFxTF56XOLtEBLx+/ttFm7ib1pLUFF5a8wUeonbDpLBtrdW6tyEYBOAtWhzlwZGUJBRoYl5cU1lAgX/j9fo/rE81n6zSr5r7WR4QrLbkHl5ELFKj6Gn3SNLoNg7ODlrubcuWkLPJZTXWdvqHyHiRlQQ5AzsyFKptF76D4YNcMGhMa+f/6Nyf2ZRZS+lbyXmwI78cB7uNsjWy8Wy48eiN6yTaDHWur8LAH4cQcYyV1TSANTf2DGOWWNl9O1T2eocsDZiTkqNDYCtVIwK1Gi6GajOh26fkiK6M+EHrx02FHbkgvi1CJVEZPp2j55KcAJsV/0ReDSUVrvto8W1ERbQMOoi5Ya2zp6lNNhETHlciOfg2MzStNpAH8KcqiKkkbJKvvlD449oMNEvSvIunM5v9r2khLro1D3VMj4HXtKCpHn3bwjmAIP1LZZAwF6LZx4JX+K+zPxTIRv5sBZEZ2tQyPs4Mq/MWbi9EMdcev97RaH6UDHXDDJHH2AQ58k/fN1MGOSIzIoNwLzpel7vVOVUv6nSczIlH5qZEbbRQepTCQ+ZQXRwOwJb0eAcxmMkbQYHsrYPJrK480gOVdVexexw=
conda_forge_output_validation: true
